# src/Blogger/BlogBundle/Resources/config/routing.yml
BlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method:  GET
        
BlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
