BlogBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isPublished:
            type: boolean
            column: isPublished
        title:
            type: string
            length: 255
        content:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
