<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
    public function recherche($chaine)
    {
        
        $qb = $this->createQueryBuilder('u')
        
        ->select('u')
        ->where('u.title like :chaine')
        ->orderBy('u.id')
        ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()->getResult();
        
    }
    
    
}
